branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - name: dev
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: docs/CHANGELOG.md
  - - "@semantic-release/exec"
    - verifyReleaseCmd:  echo "${nextRelease.version}" > .VERSION
  - - '@semantic-release/git'
    - assets:
        - docs/CHANGELOG.md
