on:
  push:
    branches:
      - dev
      - main
      - next
      - next-major
      - '*.*.x'
      - '*.x.x'
      - '*.x'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install semantic-release plugins
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/exec
      - name: Get new version
        run: |
          npx semantic-release --dry-run
          test -e .VERSION || touch .NORELEASE
      - name: Release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Publish to NuGet if release is detected
        run: |
          test -e .NORELEASE || dotnet pack -p:Version=$(cat .VERSION) -p:SymbolPackageFormat=snupkg -c Release --include-symbols -o . && \
          dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
